import {
  AdminUser,
  AdminProject,
  AdminInvoice,
  AdminChat,
  SystemAlert,
  AnalyticsData,
  AuditLog,
  SystemSettings,
  Permission,
} from "./admin-types";

export const adminPermissions: Permission[] = [
  {
    id: "users.view",
    name: "View Users",
    category: "users",
    description: "View user profiles and information",
  },
  {
    id: "users.edit",
    name: "Edit Users",
    category: "users",
    description: "Edit user profiles and roles",
  },
  {
    id: "users.delete",
    name: "Delete Users",
    category: "users",
    description: "Delete user accounts",
  },
  {
    id: "projects.view",
    name: "View Projects",
    category: "projects",
    description: "View all projects and requests",
  },
  {
    id: "projects.edit",
    name: "Edit Projects",
    category: "projects",
    description: "Edit project details and assignments",
  },
  {
    id: "projects.assign",
    name: "Assign Projects",
    category: "projects",
    description: "Assign projects to designers",
  },
  {
    id: "invoices.view",
    name: "View Invoices",
    category: "invoices",
    description: "View all invoices and payments",
  },
  {
    id: "invoices.create",
    name: "Create Invoices",
    category: "invoices",
    description: "Create and send invoices",
  },
  {
    id: "content.edit",
    name: "Edit Content",
    category: "content",
    description: "Edit website content and pages",
  },
  {
    id: "analytics.view",
    name: "View Analytics",
    category: "analytics",
    description: "View system analytics and reports",
  },
  {
    id: "system.settings",
    name: "System Settings",
    category: "system",
    description: "Manage system settings and configuration",
  },
];

export const mockAdminUsers: AdminUser[] = [
  {
    id: "admin-1",
    name: "Sarah Chen",
    email: "sarah@designrequests.com",
    role: "super-admin",
    avatar: "/placeholder.svg",
    status: "active",
    lastLogin: "2024-01-25T14:30:00Z",
    createdAt: "2023-01-01T00:00:00Z",
    permissions: adminPermissions,
  },
  {
    id: "admin-2",
    name: "Mike Rodriguez",
    email: "mike@designrequests.com",
    role: "admin",
    avatar: "/placeholder.svg",
    status: "active",
    lastLogin: "2024-01-25T12:15:00Z",
    createdAt: "2023-02-15T00:00:00Z",
    permissions: adminPermissions.filter((p) => p.category !== "system"),
  },
  {
    id: "designer-1",
    name: "Emma Wilson",
    email: "emma@designrequests.com",
    role: "designer",
    avatar: "/placeholder.svg",
    status: "active",
    lastLogin: "2024-01-25T13:45:00Z",
    createdAt: "2023-03-20T00:00:00Z",
    permissions: adminPermissions.filter((p) =>
      ["projects", "invoices"].includes(p.category),
    ),
    skills: ["Logo Design", "Branding", "Web Design"],
    assignedProjects: ["proj-1", "proj-3"],
  },
  {
    id: "designer-2",
    name: "David Kim",
    email: "david@designrequests.com",
    role: "designer",
    avatar: "/placeholder.svg",
    status: "active",
    lastLogin: "2024-01-25T11:20:00Z",
    createdAt: "2023-04-10T00:00:00Z",
    permissions: adminPermissions.filter((p) =>
      ["projects", "invoices"].includes(p.category),
    ),
    skills: ["3D Design", "Animation", "Motion Graphics"],
    assignedProjects: ["proj-2"],
  },
  {
    id: "user-1",
    name: "Alex Designer",
    email: "alex@example.com",
    role: "user",
    avatar: "/placeholder.svg",
    status: "active",
    lastLogin: "2024-01-25T10:00:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    permissions: [],
  },
];

export const mockAdminProjects: AdminProject[] = [
  {
    id: "proj-1",
    title: "Modern Logo Design for TechFlow",
    clientId: "user-1",
    clientName: "Alex Designer",
    designerId: "designer-1",
    designerName: "Emma Wilson",
    status: "in-progress",
    priority: "high",
    category: "logo",
    dueDate: "2024-02-01T00:00:00Z",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-25T14:00:00Z",
    estimatedHours: 8,
    actualHours: 5.5,
    budget: 299,
    timeline: [
      {
        id: "tl-1",
        type: "created",
        description: "Project created by client",
        timestamp: "2024-01-20T10:00:00Z",
        userId: "user-1",
        userName: "Alex Designer",
      },
      {
        id: "tl-2",
        type: "assigned",
        description: "Assigned to Emma Wilson",
        timestamp: "2024-01-20T14:30:00Z",
        userId: "admin-1",
        userName: "Sarah Chen",
      },
      {
        id: "tl-3",
        type: "status-change",
        description: "Status changed to in-progress",
        timestamp: "2024-01-22T09:00:00Z",
        userId: "designer-1",
        userName: "Emma Wilson",
      },
    ],
    tasks: [
      {
        id: "task-1",
        title: "Initial concept sketches",
        description: "Create 3-5 initial logo concepts",
        assigneeId: "designer-1",
        assigneeName: "Emma Wilson",
        status: "completed",
        dueDate: "2024-01-23T00:00:00Z",
        createdAt: "2024-01-20T14:30:00Z",
      },
      {
        id: "task-2",
        title: "Client feedback review",
        description: "Review client feedback and iterate",
        assigneeId: "designer-1",
        assigneeName: "Emma Wilson",
        status: "in-progress",
        dueDate: "2024-01-26T00:00:00Z",
        createdAt: "2024-01-24T10:00:00Z",
      },
    ],
    assets: [
      {
        id: "asset-1",
        name: "brand-guidelines.pdf",
        type: "reference",
        url: "/placeholder.svg",
        size: 2048000,
        uploadedBy: "user-1",
        uploadedAt: "2024-01-20T10:15:00Z",
        mimeType: "application/pdf",
      },
      {
        id: "asset-2",
        name: "logo-concepts-v1.png",
        type: "deliverable",
        url: "/placeholder.svg",
        size: 1024000,
        uploadedBy: "designer-1",
        uploadedAt: "2024-01-23T16:30:00Z",
        mimeType: "image/png",
      },
    ],
  },
  {
    id: "proj-2",
    title: "3D Product Visualization",
    clientId: "user-2",
    clientName: "Tech Startup Inc",
    designerId: "designer-2",
    designerName: "David Kim",
    status: "needs-feedback",
    priority: "medium",
    category: "3d",
    dueDate: "2024-02-05T00:00:00Z",
    createdAt: "2024-01-18T00:00:00Z",
    updatedAt: "2024-01-25T11:00:00Z",
    estimatedHours: 12,
    actualHours: 8,
    budget: 599,
    timeline: [],
    tasks: [],
    assets: [],
  },
];

export const mockAdminInvoices: AdminInvoice[] = [
  {
    id: "inv-1",
    projectId: "proj-1",
    projectTitle: "Modern Logo Design for TechFlow",
    clientId: "user-1",
    clientName: "Alex Designer",
    status: "sent",
    amount: 299,
    lineItems: [
      {
        id: "li-1",
        description: "Logo Design - Initial Concepts",
        quantity: 1,
        rate: 199,
        amount: 199,
        type: "design",
      },
      {
        id: "li-2",
        description: "Revisions and Refinements",
        quantity: 2,
        rate: 50,
        amount: 100,
        type: "revision",
      },
    ],
    createdAt: "2024-01-24T00:00:00Z",
    sentAt: "2024-01-24T10:00:00Z",
    dueDate: "2024-02-08T00:00:00Z",
    taxRate: 0.08,
  },
  {
    id: "inv-2",
    projectId: "proj-2",
    projectTitle: "3D Product Visualization",
    clientId: "user-2",
    clientName: "Tech Startup Inc",
    status: "draft",
    amount: 599,
    lineItems: [
      {
        id: "li-3",
        description: "3D Modeling and Rendering",
        quantity: 1,
        rate: 599,
        amount: 599,
        type: "design",
      },
    ],
    createdAt: "2024-01-25T00:00:00Z",
    dueDate: "2024-02-10T00:00:00Z",
  },
];

export const mockSystemAlerts: SystemAlert[] = [
  {
    id: "alert-1",
    type: "warning",
    title: "High server load detected",
    message: "Server response times have increased by 25% in the last hour",
    timestamp: "2024-01-25T14:30:00Z",
    isRead: false,
    source: "system",
  },
  {
    id: "alert-2",
    type: "info",
    title: "New payment received",
    message: "Payment of $299 received for Invoice #inv-3",
    timestamp: "2024-01-25T13:15:00Z",
    isRead: true,
    actionUrl: "/admin/invoices/inv-3",
    source: "payment",
  },
  {
    id: "alert-3",
    type: "error",
    title: "Failed to send email notification",
    message: "Email delivery failed for user alex@example.com",
    timestamp: "2024-01-25T12:45:00Z",
    isRead: false,
    source: "system",
  },
];

export const mockAnalyticsData: AnalyticsData = {
  clientEngagement: {
    activeSessions: 24,
    requestsPerWeek: 18,
    averageProjectValue: 425,
    clientRetentionRate: 0.85,
  },
  designerProductivity: {
    averageTurnaroundTime: 4.2,
    completedRequestsThisMonth: 32,
    utilizationRate: 0.78,
    customerSatisfaction: 4.7,
  },
  financialMetrics: {
    monthlyRecurringRevenue: 12500,
    averageInvoiceSize: 385,
    outstandingBalance: 2850,
    collectionRate: 0.94,
  },
  systemHealth: {
    uptime: 0.999,
    errorRate: 0.003,
    averageLoadTime: 1.2,
    activeUsers: 156,
  },
};

export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    userId: "admin-1",
    userName: "Sarah Chen",
    action: "user.role.changed",
    resource: "user",
    resourceId: "designer-1",
    details: {
      oldRole: "user",
      newRole: "designer",
      reason: "Promoted to designer role",
    },
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    timestamp: "2024-01-25T14:30:00Z",
    severity: "medium",
  },
  {
    id: "audit-2",
    userId: "admin-2",
    userName: "Mike Rodriguez",
    action: "project.assigned",
    resource: "project",
    resourceId: "proj-1",
    details: {
      designerId: "designer-1",
      designerName: "Emma Wilson",
    },
    ipAddress: "192.168.1.101",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    timestamp: "2024-01-25T13:15:00Z",
    severity: "low",
  },
];

export const mockSystemSettings: SystemSettings = {
  company: {
    name: "Design Requests",
    logo: "/placeholder.svg",
    email: "hello@designrequests.com",
    phone: "+1 (555) 123-4567",
    address: "123 Design Street, Creative City, CC 12345",
    website: "https://designrequests.com",
  },
  business: {
    currency: "USD",
    taxRate: 0.08,
    timezone: "America/New_York",
    language: "en",
    fiscalYearStart: "01-01",
  },
  integrations: {
    paypal: {
      enabled: true,
      clientId: "AXnSEm...",
      webhookUrl: "https://api.designrequests.com/webhooks/paypal",
    },
    email: {
      provider: "smtp",
      smtpHost: "smtp.gmail.com",
      smtpPort: 587,
      username: "noreply@designrequests.com",
    },
    analytics: {
      googleAnalytics: "GA-123456789",
      mixpanel: "1234567890abcdef",
    },
  },
  features: {
    maintenanceMode: false,
    registrationEnabled: true,
    chatEnabled: true,
    notificationsEnabled: true,
  },
};
