// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnmygswmvzxnkqhcslhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubXlnc3dtdnp4bmtxaGNzbGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NzE4NTMsImV4cCI6MjA2NzU0Nzg1M30.AE6FceXR3OBPDIld2asKXdcOTYdYpC8VuWs_zW3VnoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});